name: CI

on: [pull_request]

env:
  DEVELOPER_DIR: /Applications/Xcode_12.4.0.app

jobs:
  test:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Xcode list
      run: ls /Applications | grep 'Xcode'
    - name: Test
      run: xcodebuild test -project AccessibilitySampler.xcodeproj -scheme AccessibilitySampler -sdk iphonesimulator -destination "OS=14.4,name=iPhone 12,platform=iOS Simulator"
